apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-helm-dev
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev-helm-app1
            namespace: dev
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: nginx=192.168.121.14/helm/nginx:~0.5
        argocd-image-updater.argoproj.io/nginx.update-strategy: latest
        argocd-image-updater.argoproj.io/write-back-method: argocd
        notifications.argoproj.io/subscribe.on-deployed.slack: notifications
        notifications.argoproj.io/subscribe.on-sync-failed.slack: notifications
        notifications.argoproj.io/subscribe.on-health-degraded.slack: notifications
    spec:
      project: development
      destination:
        server: https://192.168.121.16:6443
        namespace: '{{namespace}}'
      sources:
        # Helm repository
        - repoURL: '192.168.121.14/helm'
          chart: nginx-chart
          targetRevision: "*"
          helm:
            valueFiles:
              - '$valuesrepo/helm/environments/dev/dev-values.yaml'
        # Value files repository
        - repoURL: 'https://github.com/fabioffalcao/k8s.git'
          targetRevision: main
          ref: valuesrepo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
