apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  creationTimestamp: null
  labels:
    app: nginx-local
    role: webserver
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-local
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-local
    spec:
      containers:
      - image: 192.168.121.14/local/nginx-custom:1.0
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 200Mi
status: {}
